local color =
{
	fg               = "#bdb8ad",    -- Primary text
	faded_text       = "#6c6963",
	bg               = "#282828",
	window           = "none",
	cursor_line      = "#282828",
	menu_select_line = "#333333",
	visual           = "#505050",
	bracket_match    = "#D19A66",
	search           = "#D19A66",
	warning          = "#E5C07B",
	errors           = "#BA5F5F",
	tab              = "#83B95D",

	-- syntax
	brackets         = "#6c6963",
	namespace        = "#BA5F5F",
	strings          = "#83B95D",
	functions        = "#589DCA",
	classes          = "#E5C07B",
	numbers          = "#D19A66",
	builtins         = "#b785e0",
	pink             = "#D6A99D",
	operators        = "#8bb1ca",

}



local config =
{

	syntax = -- LSP, Treesitter, Regex
	{
		variable       = { fg = color.fg },
		parameter      = { fg = color.fg },
		property       = { fg = color.fg, italic = true },
		field          = { fg = color.fg },
		builtin        = { fg = color.namespace },
		constant       = { fg = color.numbers, bold = true },
		number         = { fg = color.numbers },
		boolean        = { fg = color.numbers },
		string         = { fg = color.strings },
		character      = { fg = color.strings },
		string_escape  = { fg = color.namespace },
		string_special = { fg = color.pink },
		func           = { fg = color.functions },
		method         = { fg = color.functions, italic = true },
		constructor    = { fg = color.classes },
		type           = { fg = color.classes },
		type_builtin   = { fg = color.builtins },
		namespace      = { fg = color.namespace },
		module         = { fg = color.namespace },
		keyword        = { fg = color.builtins },
		keyword_import = { fg = color.builtins },
		keyword_mod    = { fg = color.builtins },
		operator       = { fg = color.operators },
		comment        = { fg = color.faded_text, italic = true },
		macro          = { fg = color.numbers },
		enum           = { fg = color.classes },
		enum_member    = { fg = color.numbers },
		tag            = { fg = color.builtins },
		attribute      = { fg = color.functions },
		label          = { fg = color.classes },
		preproc        = { fg = color.builtins },
		punctuation    = { fg = color.brackets },
	},
	core =
	{
		Normal           = { fg = color.fg, bg = color.window },
		NormalFloat      = { fg = color.fg, bg = color.window },
		CursorLine       = { bg = color.cursor_line },
		CursorColumn     = { bg = color.cursor_line },
		CursorLineNr     = { fg = color.fg, bold = true },
		LineNr           = { fg = color.faded_text },
		SignColumn       = { bg = color.window },
		Visual           = { bg = color.visual },
		WinSeparator     = { fg = color.fg },
		VertSplit        = { fg = color.fg },
		Search           = { fg = color.bg, bg = color.search },
		IncSearch        = { fg = color.bg, bg = color.search },
		StatusLine       = { fg = color.fg, bg = color.menu_select_line },
		StatusLineNC     = { fg = color.fg, bg = color.bg },
		TabLine          = { fg = color.fg, bg = color.menu_select_line },
		TabLineFill      = { bg = color.bg },
		TabLineSel       = { fg = color.bg, bg = color.tab },
		Pmenu            = { fg = color.fg, bg = color.window },
		PmenuSel         = { bg = color.menu_select_line },
		PmenuSbar        = { bg = color.window },
		PmenuThumb       = { bg = color.fg },
		FloatBorder      = { fg = color.fg, bg = color.window },
		EndOfBuffer      = { fg = color.bg },
		Whitespace       = { fg = color.faded_text },
		Folded           = { fg = color.fg, bg = color.fg },
		FoldColumn       = { fg = color.fg },
		MatchParen       = { bg = color.visual, fg = color.bracket_match, bold = true },
		NotifyBackground = { bg = color.bg }
	},
	diagnostics = --LSP diagnostics
	{
		DiagnosticError            = { fg = color.errors },
		DiagnosticWarn             = { fg = color.warning },
		DiagnosticInfo             = { fg = color.warning },
		DiagnosticHint             = { fg = color.faded_text },
		DiagnosticUnderlineError   = { sp = color.errors, undercurl = true },
		DiagnosticUnderlineWarn    = { sp = color.warning, undercurl = true },
		DiagnosticUnderlineInfo    = { sp = color.faded_text, undercurl = true },
		DiagnosticUnderlineHint    = { sp = color.faded_text, undercurl = true },
		DiagnosticVirtualTextError = { fg = color.errors },
		DiagnosticVirtualTextWarn  = { fg = color.warning },
		DiagnosticVirtualTextInfo  = { fg = color.faded_text },
		DiagnosticVirtualTextHint  = { fg = color.faded_text },
	},
	lsp = -- LSP REFERENCES + INLAY HINTS
	{
		LspReferenceText  = { bg = color.visual },
		LspReferenceRead  = { bg = color.visual },
		LspReferenceWrite = { bg = color.visual },
		LspInlayHint      = { fg = color.faded_text, italic = true },
	},
	git = -- git integration
	{
		DiffAdd        = { fg = "#83B95D" },
		DiffChange     = { fg = "#E5C07B" },
		DiffDelete     = { fg = "#BA5F5F" },
		DiffText       = { fg = "#589DCA" },
		GitSignsAdd    = { fg = "#83B95D" },
		GitSignsChange = { fg = "#E5C07B" },
		GitSignsDelete = { fg = "#BA5F5F" },
	},
	markup =
	{
		["@markup.heading"]  = { fg = color.numbers },
		["@markup.quote"]    = { fg = color.strings },
		["@markup.link"]     = { fg = color.functions },
		["@markup.link.url"] = { fg = color.functions },
		["Special"]          = { fg = "#83B95D" },
	},
	telescope =
	{
		TelescopeNormal       = { fg = color.fg, bg = color.window },
		TelescopeBorder       = { bg = color.window },
		TelescopeSelection    = { bg = color.menu_select_line },
		TelescopeMatching     = { fg = "#83B95D" },
		TelescopePromptNormal = { bg = color.window },
		TelescopePromptBorder = { bg = color.window },
		TelescopePromptPrefix = { fg = color.fg },
		TelescopeTitle        = { fg = color.fg },
	},
	dap =
	{
		DapBreakpoint = { fg = "#589DCA" },
		DapBreakpointCondition = { fg = "#D19A66" },
		DapLogPoint = { fg = "#BA5F5F" },
		DapStopped = { fg = "#83B95D" },
	}
}
config.blink =
{
	BlinkCmpKindText          = config.syntax.variable,
	BlinkCmpKindMethod        = config.syntax.method,
	BlinkCmpKindFunction      = config.syntax.func,
	BlinkCmpKindConstructor   = config.syntax.constructor,
	BlinkCmpKindField         = config.syntax.property,
	BlinkCmpKindVariable      = config.syntax.variable,
	BlinkCmpKindClass         = config.syntax.type,
	BlinkCmpKindInterface     = config.syntax.type,
	BlinkCmpKindModule        = config.syntax.module,
	BlinkCmpKindProperty      = config.syntax.property,
	BlinkCmpKindUnit          = config.syntax.number,
	BlinkCmpKindValue         = config.syntax.number,
	BlinkCmpKindEnum          = config.syntax.enum,
	BlinkCmpKindEnumMember    = config.syntax.enum_member,
	BlinkCmpKindKeyword       = config.syntax.keyword,
	BlinkCmpKindSnippet       = { fg = "#E5C07B" },
	BlinkCmpKindColor         = { fg = "#E5C07B" },
	BlinkCmpKindFile          = { fg = "#E5C07B" },
	BlinkCmpKindFolder        = { fg = "#589DCA" },
	BlinkCmpKindReference     = { fg = "#E5C07B" },
	BlinkCmpKindConstant      = config.syntax.constant,
	BlinkCmpKindStruct        = config.syntax.type,
	BlinkCmpKindEvent         = { fg = "#E5C07B" },
	BlinkCmpKindOperator      = config.syntax.operator,
	BlinkCmpKindTypeParameter = config.syntax.parameter,
}
return config
