local color =
{
    fg                  = "#b3a690",
    -- bg                  = "#282828",
    bg                  = "none",
    cursor_line         = "#303030",
    menu_select_line    = "#3f3f3f",
    visual              = "#505050",
    bracket_match       = "#D19A66",
    search              = "#D19A66",
    warning             = "#E5C07B",
    errors              = "#BA5F5F",
    primary_text        = "#bdb8ad",
    secondary_text      = "#6c6963",
    tab                 = "#83B95D",
    -- syntax
    white               = "#bdb8ad",
    gray                = "#6c6963",
    red                 = "#BA5F5F",
    green               = "#83B95D",
    blue                = "#589DCA",
    yellow              = "#E5C07B",
    orange              = "#D19A66",
    purple              = "#A785C3",
    pink                = "#D6A99D",
}

local config =
{

    syntax = -- LSP, Treesitter, Regex
    {
        variable                    = { fg = color.white },
        parameter                   = { fg = color.white },
        property                    = { fg = color.white, italic = true },
        field                       = { fg = color.white },
        builtin                     = { fg = color.red },
        constant                    = { fg = color.orange, bold = true },
        number                      = { fg = color.orange },
        boolean                     = { fg = color.orange },
        string                      = { fg = color.green },
        character                   = { fg = color.green },
        string_escape               = { fg = color.red },
        string_special              = { fg = color.pink },
        func                        = { fg = color.blue },
        method                      = { fg = color.blue, italic = true},
        constructor                 = { fg = color.yellow },
        type                        = { fg = color.yellow },
        type_builtin                = { fg = color.purple },
        namespace                   = { fg = color.red },
        module                      = { fg = color.red },
        keyword                     = { fg = color.purple },
        keyword_import              = { fg = color.purple },
        keyword_mod                 = { fg = color.purple },
        operator                    = { fg = color.purple },
        comment                     = { fg = color.gray, italic = true },
        macro                       = { fg = color.orange },
        enum                        = { fg = color.yellow },
        enum_member                 = { fg = color.orange },
        tag                         = { fg = color.purple },
        attribute                   = { fg = color.blue },
        label                       = { fg = color.yellow },
        preproc                     = { fg = color.purple },
        punctuation                 = { fg = color.gray },
    },
    core =
    {
        Normal                      = { fg = color.fg, bg = color.bg },
        NormalFloat                 = { fg = color.fg, bg = color.bg },
        CursorLine                  = { bg = color.cursor_line },
        CursorColumn                = { bg = color.cursor_line },
        CursorLineNr                = { fg = color.fg, bold = true },
        LineNr                      = { fg = color.secondary_text },
        SignColumn                  = { bg = color.bg },
        Visual                      = { bg = color.visual },
        WinSeparator                = { fg = color.fg },
        VertSplit                   = { fg = color.fg },
        Search                      = { fg = color.bg, bg = color.search },
        IncSearch                   = { fg = color.bg, bg = color.search },
        StatusLine                  = { fg = color.primary_text, bg = color.menu_select_line },
        StatusLineNC                = { fg = color.primary_text, bg = color.bg },
        TabLine                     = { fg = color.primary_text, bg = color.menu_select_line },
        TabLineFill                 = { bg = color.bg },
        TabLineSel                  = { fg = color.bg, bg = color.tab },
        Pmenu                       = { fg = color.primary_text, bg = color.bg },
        PmenuSel                    = { bg = color.menu_select_line },
        PmenuSbar                   = { bg = color.fg },
        PmenuThumb                  = { bg = color.fg },
        FloatBorder                 = { fg = color.fg, bg = color.bg },
        EndOfBuffer                 = { fg = color.bg },
        Whitespace                  = { fg = color.secondary_text },
        Folded                      = { fg = color.fg, bg = color.fg },
        FoldColumn                  = { fg = color.fg },
        MatchParen                  = { bg = color.visual, fg = color.bracket_match, bold = true },
    },
    diagnostics = --LSP diagnostics
    {
        DiagnosticError             = { fg = color.errors },
        DiagnosticWarn              = { fg = color.warning },
        DiagnosticInfo              = { fg = color.warning },
        DiagnosticHint              = { fg = color.secondary_text },
        DiagnosticUnderlineError    = { sp = color.errors, undercurl = true },
        DiagnosticUnderlineWarn     = { sp = color.warning, undercurl = true },
        DiagnosticUnderlineInfo     = { sp = color.secondary_text, undercurl = true },
        DiagnosticUnderlineHint     = { sp = color.secondary_text, undercurl = true },
        DiagnosticVirtualTextError  = { fg = color.errors },
        DiagnosticVirtualTextWarn   = { fg = color.warning },
        DiagnosticVirtualTextInfo   = { fg = color.secondary_text },
        DiagnosticVirtualTextHint   = { fg = color.secondary_text },
    },
    lsp = -- LSP REFERENCES + INLAY HINTS
    {
        LspReferenceText            = { bg = color.visual },
        LspReferenceRead            = { bg = color.visual },
        LspReferenceWrite           = { bg = color.visual },
        LspInlayHint                = { fg = color.secondary_text, italic = true },
    },
    git = -- git integration
    {
        DiffAdd                     = { fg = "#83B95D" },
        DiffChange                  = { fg = "#E5C07B"  },
        DiffDelete                  = { fg =  "#BA5F5F" },
        DiffText                    = { fg =  "#589DCA" },
        GitSignsAdd                 = { fg = "#83B95D"  },
        GitSignsChange              = { fg = "#E5C07B" },
        GitSignsDelete              = { fg = "#BA5F5F" },
    },
    markup =
    {
        ["@markup.heading"]         = { fg = color.orange },
        ["@markup.quote"]           = { fg = color.green },
        ["@markup.link"]            = { fg = color.blue },
        ["@markup.link.url"]        = { fg = color.blue },
    },
    telescope =
    {
        TelescopeNormal             = {fg = color.primary_text, bg = color.bg },
        TelescopeBorder             = { bg = color.bg },
        TelescopeSelection          = { bg = color.menu_select_line },
        TelescopeMatching           = { fg = "#83B95D"},
        TelescopePromptNormal       = { bg = color.bg },
        TelescopePromptBorder       = { bg = color.bg },
        TelescopePromptPrefix       = { fg = color.primary_text },
        TelescopeTitle              = { fg = color.primary_text },
    }
}
config.blink =
{
    BlinkCmpKindText                = config.syntax.variable,
    BlinkCmpKindMethod              = config.syntax.method,
    BlinkCmpKindFunction            = config.syntax.func,
    BlinkCmpKindConstructor         = config.syntax.constructor,
    BlinkCmpKindField               = config.syntax.property,
    BlinkCmpKindVariable            = config.syntax.variable,
    BlinkCmpKindClass               = config.syntax.type,
    BlinkCmpKindInterface           = config.syntax.type,
    BlinkCmpKindModule              = config.syntax.module,
    BlinkCmpKindProperty            = config.syntax.property,
    BlinkCmpKindUnit                = config.syntax.number,
    BlinkCmpKindValue               = config.syntax.number,
    BlinkCmpKindEnum                = config.syntax.enum,
    BlinkCmpKindEnumMember          = config.syntax.enum_member,
    BlinkCmpKindKeyword             = config.syntax.keyword,
    BlinkCmpKindSnippet             = { fg = "#E5C07B" },
    BlinkCmpKindColor               = { fg = "#E5C07B"  },
    BlinkCmpKindFile                = { fg =  "#E5C07B" },
    BlinkCmpKindFolder              = { fg = "#589DCA" },
    BlinkCmpKindReference           = { fg = "#E5C07B" },
    BlinkCmpKindConstant            = config.syntax.constant,
    BlinkCmpKindStruct              = config.syntax.type,
    BlinkCmpKindEvent               = { fg = "#E5C07B" },
    BlinkCmpKindOperator            = config.syntax.operator,
    BlinkCmpKindTypeParameter       = config.syntax.parameter,
}
return config
